#------------project configuration start----------------#
openie_llm: &openie_llm
  api_key: empty
  base_url: http://127.0.0.1:11434/v1
  model: qwen2.5:7b
  type: maas
#以上是，知识抽取模型。这里均用本地ollama，因此apikey是空，baseurl是ollama端口
chat_llm: &chat_llm
  api_key: empty
  base_url: http://127.0.0.1:11434/v1
  model: qwen2.5:7b
  type: maas
#对话模型
vectorize_model: &vectorize_model
  api_key: empty
  base_url: http://127.0.0.1:11434/v1
  model: bge-m3:latest
  type: openai
  vector_dimensions: 1536
vectorizer: *vectorize_model
#向量化模型。这个必须是专门的向量化模型
log:
  level: INFO
#报告等级（info或debug）
project:
  biz_scene: default
  host_addr: http://127.0.0.1:8887
  id: '2'
  language: zh
  namespace: Lawkag1
#以上是项目信息。namespace就是命名空间，即知识图谱项目名称，应当修改
#------------project configuration end----------------#

#------------kag-builder configuration start----------------#
kag_builder_pipeline:
  chain:
    type: unstructured_builder_chain # 这个后面是路径，从kag文件夹开始向内：kag.builder.default_chain.DefaultUnstructuredBuilderChain
    extractor:
      type: schema_constraint_extractor #(schema严格约束抽取器或schema自由抽取器） kag.builder.component.extractor.schema_free_extractor.SchemaFreeExtractor
      llm: *openie_llm
      #prompt部分是可以修改的！
      ner_prompt:
        type: ner #（命名实体识别prompt) kag.builder.prompt.default.ner.OpenIENERPrompt
      std_prompt:
        type: std # (标准化prompt）kag.builder.prompt.default.std.OpenIEEntitystandardizationdPrompt
      triple_prompt:
        type: triple # （三元组识别prompt)kag.builder.prompt.default.triple.OpenIETriplePrompt
    reader:
      type: txt_reader #（输入格式reader，对docx等格式均有不同） kag.builder.component.reader.dict_reader.txt_reader
    post_processor:
      type: kag_post_processor #（默认后处理器） kag.builder.component.postprocessor.kag_postprocessor.KAGPostProcessor
      similarity_threshold: 0.9
    splitter:
      type: length_splitter # kag.builder.component.splitter.length_splitter.LengthSplitter
      split_length: 800
      window_length: 100
    vectorizer:
      type: batch_vectorizer # kag.builder.component.vectorizer.batch_vectorizer.BatchVectorizer
      vectorize_model: *vectorize_model
    writer:
      type: kg_writer # kag.builder.component.writer.kg_writer.KGWriter
  num_threads_per_chain: 1
  num_chains: 16
  scanner:
    type: file_scanner # kag.builder.component.scanner.dataset_scanner.file_scanner
#------------kag-builder configuration end----------------#

#------------kag-solver configuration start----------------#
search_api: &search_api
  type: openspg_search_api #kag.solver.tools.search_api.impl.openspg_search_api.OpenSPGSearchAPI

graph_api: &graph_api
  type: openspg_graph_api #kag.solver.tools.graph_api.impl.openspg_graph_api.OpenSPGGraphApi

exact_kg_retriever: &exact_kg_retriever
  type: default_exact_kg_retriever # kag.solver.retriever.impl.default_exact_kg_retriever.DefaultExactKgRetriever
  el_num: 5
  llm_client: *chat_llm
  search_api: *search_api
  graph_api: *graph_api

fuzzy_kg_retriever: &fuzzy_kg_retriever
  type: default_fuzzy_kg_retriever # kag.solver.retriever.impl.default_fuzzy_kg_retriever.DefaultFuzzyKgRetriever
  el_num: 5
  vectorize_model: *vectorize_model
  llm_client: *chat_llm
  search_api: *search_api
  graph_api: *graph_api

chunk_retriever: &chunk_retriever
  type: default_chunk_retriever # kag.solver.retriever.impl.default_fuzzy_kg_retriever.DefaultFuzzyKgRetriever
  llm_client: *chat_llm
  recall_num: 10
  rerank_topk: 10

kag_solver_pipeline:
  memory:
    type: default_memory # kag.solver.implementation.default_memory.DefaultMemory
    llm_client: *chat_llm
  max_iterations: 3
  reasoner:
    type: default_reasoner # kag.solver.implementation.default_reasoner.DefaultReasoner
    llm_client: *chat_llm
    lf_planner:
      type: default_lf_planner # kag.solver.plan.default_lf_planner.DefaultLFPlanner
      llm_client: *chat_llm
      vectorize_model: *vectorize_model
    lf_executor:
      type: default_lf_executor # kag.solver.execute.default_lf_executor.DefaultLFExecutor
      llm_client: *chat_llm
      force_chunk_retriever: true
      exact_kg_retriever: *exact_kg_retriever
      fuzzy_kg_retriever: *fuzzy_kg_retriever
      chunk_retriever: *chunk_retriever
      merger:
        type: default_lf_sub_query_res_merger # kag.solver.execute.default_sub_query_merger.DefaultLFSubQueryResMerger
        vectorize_model: *vectorize_model
        chunk_retriever: *chunk_retriever
  generator:
    type: default_generator # kag.solver.implementation.default_generator.DefaultGenerator
    llm_client: *chat_llm
    generate_prompt:
      type: default_resp_generator # kag.solver.prompt.default.resp_generator.RespGenerator
  reflector:
    type: default_reflector # kag.solver.implementation.default_reflector.DefaultReflector
    llm_client: *chat_llm

#------------kag-solver configuration end----------------#
